server:
  port: 8081
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
management:
#  endpoints:
#    web:
#      exposure:
#        # @see https://spring.pleiades.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.exposing
#        include: metrics,health,flyway,env,beans,configprops
  endpoint:
    health:
      show-details: always
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-description: Initial
#    @see org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
#    locations: "classpath:db/migration"
# パラメータの値をログに表示 ex.) binding parameter [1] as [INTEGER] - [1]
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
